name: Test Notification Workflow

on:
  push:
    branches: [main, develop]
  workflow_dispatch:  # Allows manual triggering

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test-notification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Get full history

      - name: "Send Release Notification on Task Asana"
        run: |
          # Extract PR number from merge commit message
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          PR_NUMBER=$(echo "$COMMIT_MESSAGE" | grep -oP '#\K\d+')
          
          if [ -n "$PR_NUMBER" ]; then
            echo "Found PR number: $PR_NUMBER"
            
            # Get PR body using GitHub API
            PR_BODY=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER" | \
              jq -r '.body // ""')
            
            # Extract Asana task ID from PR body (supports both /task/ and /item/)
            ASANA_TASK_ID=$(echo "$PR_BODY" | grep -oP 'https://app\.asana\.com/.*/(?:task|item)/\d+' | grep -oP '\d+$' || true)
            
            if [ -n "$ASANA_TASK_ID" ]; then
              REPO=${{ github.repository }}
              PR_URL="https://github.com/$REPO/pull/$PR_NUMBER"
              
              curl -s -X POST https://app.asana.com/api/1.0/tasks/$ASANA_TASK_ID/stories \
                -H "Authorization: Bearer ${{ secrets.ASANA_TOKEN }}" \
                -H "Content-Type: application/json" \
                -d "{\"data\": {
                      \"text\": \"Hi team,\n🚀 This has been successfully deployed to debug/beta!\n🔗 PR Link: $PR_URL\" 
                    }}"
              
              echo "Asana task updated: $ASANA_TASK_ID"
            else
              echo "No Asana task ID found in PR body — skipping notification."
            fi
          else
            echo "No PR number found in commit message — this might be a direct push."
          fi

      # - name: "Test Summary"
      #   run: |
      #     echo "🎉 Test completed successfully!"
      #     echo "📋 This workflow tested:"
      #     echo "  ✅ PR number extraction from commit messages"
      #     echo "  ✅ Asana task ID extraction from PR bodies"
      #     echo "  ✅ Failed workflow run detection"
      #     echo "  ✅ Commit range analysis"
      #     echo ""
      #     echo "🔒 All operations were read-only and safe"
      #     echo "🚀 Ready to implement in production workflow"

      - name: "Extract changelog"
        id: extract-changelog
        uses: TheDotLabs/extract-release-notes@main

      - name: "Send Release Notifications on Asana Tasks"
        run: |
          # Extract all PR numbers from the release notes
          RELEASE_NOTES="${{ steps.extract-changelog.outputs.release_notes }}"
          PR_NUMBERS=$(echo "$RELEASE_NOTES" | grep -oP '\(#\K\d+(?=\))' | sort -u)

          if [ -z "$PR_NUMBERS" ]; then
            echo "No PR numbers found in release notes"
            exit 0
          fi

          echo "Found PR numbers: $PR_NUMBERS"

          # Loop through each PR number
          for PR_NUMBER in $PR_NUMBERS; do
            echo "Processing PR #$PR_NUMBER"

            # Get PR body using GitHub API
            PR_RESPONSE=$(curl -s -w "%{http_code}" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER")
            
            HTTP_STATUS="${PR_RESPONSE: -3}"  # Last 3 characters
            PR_BODY=$(echo "$PR_RESPONSE" | head -c -3 | jq -r '.body // ""')

            if [ "$HTTP_STATUS" != "200" ] || [ -z "$PR_BODY" ]; then
              echo "⚠️  Could not fetch PR #$PR_NUMBER body or PR does not exist. Skipping."
              continue
            fi

            # Extract Asana task ID from PR body
            ASANA_TASK_ID=$(echo "$PR_BODY" | grep -oP 'https://app\.asana\.com/.*/(?:task|item)/\K\d+' || true)

            if [ -n "$ASANA_TASK_ID" ]; then
              REPO=${{ github.repository }}
              PR_URL="https://github.com/$REPO/pull/$PR_NUMBER"

              echo "Updating Asana task $ASANA_TASK_ID for PR #$PR_NUMBER"

              curl -s -X POST https://app.asana.com/api/1.0/tasks/$ASANA_TASK_ID/stories \
                -H "Authorization: Bearer ${{ secrets.ASANA_TOKEN }}" \
                -H "Content-Type: application/json" \
                -d "{\"data\": {
                      \"text\": \"Hi team,\n🚀 This has been successfully deployed to production!\n🔗 PR Link: $PR_URL\n📦 Release: ${{ github.ref_name }}\"
                    }}"

              echo "✅ Asana task updated: $ASANA_TASK_ID"
            else
              echo "⚠️  No Asana task ID found in PR #$PR_NUMBER. Skipping."
            fi

            # Small delay to avoid rate limiting
            sleep 1
          done

          echo "Finished processing all PR numbers"














